<?php

namespace Database\Seeders;

use App\Models\Student;
use App\Models\User;
use Illuminate\Database\Seeder;

class StudentsSeeder extends Seeder
{
    public function run(): void
    {
        $parents = User::whereHas('roles', function($query) {
            $query->where('name', 'parent');
        })->get();

        $studentsData = [
            [
                'first_name' => 'Tolu',
                'last_name' => 'Williams',
                'email' => 'tolu.williams@student.com',
                'phone' => '07011111111',
                'date_of_birth' => '2012-03-15',
                'gender' => 'male',
                'address' => '1 Parent Street, Ikeja, Lagos',
                'state' => 'Lagos',
                'location' => 'Ikeja',
                'parent_name' => 'Mr. Ade Williams',
                'parent_email' => 'ade.williams@example.com',
                'parent_phone' => '08011111111',
                'enrollment_date' => '2024-01-10',
                'status' => 'active',
            ],
            [
                'first_name' => 'Chiamaka',
                'last_name' => 'Williams',
                'email' => 'chiamaka.williams@student.com',
                'phone' => '07011111112',
                'date_of_birth' => '2014-07-20',
                'gender' => 'female',
                'address' => '1 Parent Street, Ikeja, Lagos',
                'state' => 'Lagos',
                'location' => 'Ikeja',
                'parent_name' => 'Mr. Ade Williams',
                'parent_email' => 'ade.williams@example.com',
                'parent_phone' => '08011111111',
                'enrollment_date' => '2024-02-05',
                'status' => 'active',
            ],
            [
                'first_name' => 'Ayo',
                'last_name' => 'Balogun',
                'email' => 'ayo.balogun@student.com',
                'phone' => '07022222222',
                'date_of_birth' => '2011-09-10',
                'gender' => 'male',
                'address' => '2 Family Road, Victoria Island, Lagos',
                'state' => 'Lagos',
                'location' => 'Victoria Island',
                'parent_name' => 'Mrs. Funmi Balogun',
                'parent_email' => 'funmi.balogun@example.com',
                'parent_phone' => '08022222222',
                'enrollment_date' => '2023-09-15',
                'status' => 'active',
            ],
            [
                'first_name' => 'Chidinma',
                'last_name' => 'Okafor',
                'email' => 'chidinma.okafor@student.com',
                'phone' => '07033333333',
                'date_of_birth' => '2013-05-22',
                'gender' => 'female',
                'address' => '3 Guardian Avenue, Lekki, Lagos',
                'state' => 'Lagos',
                'location' => 'Lekki',
                'parent_name' => 'Mr. Chidi Okafor',
                'parent_email' => 'chidi.okafor@example.com',
                'parent_phone' => '08033333333',
                'enrollment_date' => '2024-01-20',
                'status' => 'active',
            ],
            [
                'first_name' => 'Aisha',
                'last_name' => 'Abdullahi',
                'email' => 'aisha.abdullahi@student.com',
                'phone' => '07044444444',
                'date_of_birth' => '2012-11-08',
                'gender' => 'female',
                'address' => '4 Caretaker Close, Garki, Abuja',
                'state' => 'FCT Abuja',
                'location' => 'Garki',
                'parent_name' => 'Mrs. Amina Abdullahi',
                'parent_email' => 'amina.abdullahi@example.com',
                'parent_phone' => '08044444444',
                'enrollment_date' => '2023-11-01',
                'status' => 'active',
            ],
            [
                'first_name' => 'Chukwuemeka',
                'last_name' => 'Nwosu',
                'email' => 'chukwu.nwosu@student.com',
                'phone' => '07055555555',
                'date_of_birth' => '2010-04-12',
                'gender' => 'male',
                'address' => '5 Parent Plaza, GRA, Port Harcourt',
                'state' => 'Rivers',
                'location' => 'GRA',
                'parent_name' => 'Mr. Emeka Nwosu',
                'parent_email' => 'emeka.nwosu@example.com',
                'parent_phone' => '08055555555',
                'enrollment_date' => '2023-08-20',
                'status' => 'active',
            ],
            [
                'first_name' => 'Folake',
                'last_name' => 'Adeyemi',
                'email' => 'folake.adeyemi@student.com',
                'phone' => '07066666666',
                'date_of_birth' => '2014-01-30',
                'gender' => 'female',
                'address' => '6 Family Street, Bodija, Ibadan',
                'state' => 'Oyo',
                'location' => 'Bodija',
                'parent_name' => 'Mrs. Kemi Adeyemi',
                'parent_email' => 'kemi.adeyemi@example.com',
                'parent_phone' => '08066666666',
                'enrollment_date' => '2024-03-01',
                'status' => 'active',
            ],
            [
                'first_name' => 'Yemi',
                'last_name' => 'Bakare',
                'email' => 'yemi.bakare@student.com',
                'phone' => '07077777777',
                'date_of_birth' => '2011-08-18',
                'gender' => 'male',
                'address' => '7 Guardian Way, Ogba, Lagos',
                'state' => 'Lagos',
                'location' => 'Ogba',
                'parent_name' => 'Mr. Tunde Bakare',
                'parent_email' => 'tunde.bakare@example.com',
                'parent_phone' => '08077777777',
                'enrollment_date' => '2023-10-10',
                'status' => 'active',
            ],
            [
                'first_name' => 'Adaeze',
                'last_name' => 'Eze',
                'email' => 'adaeze.eze@student.com',
                'phone' => '07088888888',
                'date_of_birth' => '2013-12-05',
                'gender' => 'female',
                'address' => '8 Parent Drive, Enugu',
                'state' => 'Enugu',
                'location' => 'Trans-Ekulu',
                'parent_name' => 'Mrs. Ngozi Eze',
                'parent_email' => 'ngozi.eze@example.com',
                'parent_phone' => '08088888888',
                'enrollment_date' => '2024-02-14',
                'status' => 'active',
            ],
            [
                'first_name' => 'Musa',
                'last_name' => 'Hassan',
                'email' => 'musa.hassan@student.com',
                'phone' => '07099999999',
                'date_of_birth' => '2012-06-25',
                'gender' => 'male',
                'address' => '9 Caretaker Court, Kaduna',
                'state' => 'Kaduna',
                'location' => 'Barnawa',
                'parent_name' => 'Mr. Yusuf Hassan',
                'parent_email' => 'yusuf.hassan@example.com',
                'parent_phone' => '08099999999',
                'enrollment_date' => '2023-12-01',
                'status' => 'active',
            ],
            [
                'first_name' => 'Chinonso',
                'last_name' => 'Obi',
                'email' => 'chinonso.obi@student.com',
                'phone' => '07010101010',
                'date_of_birth' => '2015-02-14',
                'gender' => 'male',
                'address' => '10 Family Lane, Owerri',
                'state' => 'Imo',
                'location' => 'World Bank',
                'parent_name' => 'Mrs. Grace Obi',
                'parent_email' => 'grace.obi@example.com',
                'parent_phone' => '08010101010',
                'enrollment_date' => '2024-04-01',
                'status' => 'active',
            ],
            [
                'first_name' => 'Titilayo',
                'last_name' => 'Obi',
                'email' => 'titilayo.obi@student.com',
                'phone' => '07010101011',
                'date_of_birth' => '2011-10-20',
                'gender' => 'female',
                'address' => '10 Family Lane, Owerri',
                'state' => 'Imo',
                'location' => 'World Bank',
                'parent_name' => 'Mrs. Grace Obi',
                'parent_email' => 'grace.obi@example.com',
                'parent_phone' => '08010101010',
                'enrollment_date' => '2023-09-01',
                'status' => 'active',
            ],
        ];

        foreach ($studentsData as $index => $studentData) {
            // Find parent by email
            $parent = $parents->where('email', $studentData['parent_email'])->first();

            Student::create([
                'parent_id' => $parent ? $parent->id : null,
                'student_id' => 'STU' . str_pad($index + 1, 4, '0', STR_PAD_LEFT),
                'first_name' => $studentData['first_name'],
                'last_name' => $studentData['last_name'],
                'email' => $studentData['email'],
                'phone' => $studentData['phone'],
                'date_of_birth' => $studentData['date_of_birth'],
                'gender' => $studentData['gender'],
                'address' => $studentData['address'],
                'state' => $studentData['state'],
                'location' => $studentData['location'],
                'parent_name' => $studentData['parent_name'],
                'parent_email' => $studentData['parent_email'],
                'parent_phone' => $studentData['parent_phone'],
                'enrollment_date' => $studentData['enrollment_date'],
                'status' => $studentData['status'],
            ]);
        }

        $this->command->info('Students seeded successfully!');
    }
}
